development:
  packages_list_url: 'http://cran.at.r-project.org/src/contrib/PACKAGES'
  packages_cran_url: 'http://cran.at.r-project.org/src/contrib/'


test:
  packages_list_url: 'http://cran.at.r-project.org/src/contrib/PACKAGES'
  packages_cran_url: 'http://cran.at.r-project.org/src/contrib/'